### ISSUE TITLE
Fix: ModuleInitGenesisTest

### ISSUE THREAD

**Issue by fdymylja** [allinbits/cosmos-sdk#53]
--- FAIL: TestInitGenesisOnMigration (0.00s)
    module.go:358: Unexpected call to *mocks.MockAppModule.ConsensusVersion([]) at /home/runner/work/cosmos-sdk/cosmos-sdk/tests/mocks/types_module_module.go:371 because: there are no expected calls of the method "ConsensusVersion" for that receiver
    app_test.go:208: missing call(s) to *mocks.MockAppModule.DefaultGenesis(is equal to &{0xc000fe3650}) /home/runner/work/cosmos-sdk/cosmos-sdk/simapp/app_test.go:211
    app_test.go:208: missing call(s) to *mocks.MockAppModule.InitGenesis(is equal to {0xc00011e010 {0xc000cecb10 map[0xc000112e90:0xc000ced380 0xc000112f60:0xc000cecf00 0xc000112f70:0xc000ced440 0xc000112f80:0xc000ced140 0xc000112f90:0xc000ced080 0xc000112fb0:0xc000cece40 0xc000112fd0:0xc000cecfc0 0xc000112ff0:0xc000ced2c0 0xc000113000:0xc000cecc00 0xc000113050:0xc000ced500 0xc000113060:0xc000ced200 0xc000113070:0xc000ced5c0 0xc000113080:0xc000ceccc0 0xc0001130a0:0xc000cecd80 0xc000113090:0xc000ced680] map[acc:0xc000112e90 authz:0xc000113080 bank:0xc000112f60 capability:0xc000113070 distribution:0xc000112f90 evidence:0xc000113060 feegrant:0xc000113050 gov:0xc000112fd0 mem_capability:0xc0001130a0 mint:0xc000112f80 params:0xc000112ff0 slashing:0xc000112fb0 staking:0xc000112f70 transient_params:0xc000113090 upgrade:0xc000113000] <nil> map[] map[]} {{0 0}  0 {0 0 <nil>} {[] {0 []}} [] [] [] [] [] [] [] [] []}  [] 0xc000112b60 [] 0xc000ea4560 <nil> true false [] <nil> 0xc000e9c888}, is equal to &{0xc000fe3650}, is equal to [123 34 107 101 121 34 58 32 34 118 97 108 117 101 34 125]) /home/runner/work/cosmos-sdk/cosmos-sdk/simapp/app_test.go:212

**Comment by jgimeno** [comment]
How come is it working for me @fdymylja ?

**Comment by jgimeno** [comment]
```=== RUN   TestInitGenesisOnMigration
--- PASS: TestInitGenesisOnMigration (0.00s)
PASS```

**Comment by jgimeno** [comment]
Ok, found it.

**Comment by fdymylja** [comment]
solved
